#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

if($argc > 1 && $argv[1] == 'config') {

echo <<<EOT
graph_title Freenet Java memory use
graph_args --base 1024 --lower-limit 0
graph_vlabel bytes
graph_category freenet
graph_info The Java memory use of Freenet

used.label used
used.type GAUGE
used.draw LINE
used.info Used Java memory

free.label free
free.type GAUGE
free.draw LINE
free.info Free Java memory

allocated.label allocated
allocated.type GAUGE
allocated.draw LINE
allocated.info Java allocated memory

maximum.label maximum
maximum.type GAUGE
maximum.draw LINE
maximum.info Maximum Java memory use

EOT;

} else {

echo <<<EOT
maximum.value   {$fcpData['volatile.maximumJavaMemory']}
allocated.value {$fcpData['volatile.allocatedJavaMemory']}
used.value      {$fcpData['volatile.usedJavaMemory']}
free.value      {$fcpData['volatile.freeJavaMemory']}

EOT;

}


