#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

if($argc > 1 && $argv[1] == 'config') {

$type = $conf['areastacks'] ? 'AREASTACK' : 'LINE';

echo <<<EOT
graph_title Freenet seeds
graph_args --lower-limit 0
graph_vlabel peers
graph_category freenet
graph_info Seednodes we are connected to, and nodes we are seeding for

seedingfor.label seeding for
seedingfor.type GAUGE
seedingfor.draw $type
seedingfor.info Peers we are seeding for

seednodes.label seednodes
seednodes.type GAUGE
seednodes.draw $type
seednodes.info Seednodes we are connected to


EOT;

} else {

echo <<<EOT
seedingfor.value   {$fcpData['volatile.numberOfSeedClients']}
seednodes.value        {$fcpData['volatile.numberOfSeedServers']}

EOT;

}


