#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

if($argc > 1 && $argv[1] == 'config') {

echo <<<'EOT'
graph_title Freenet bandwidth usage
graph_args --lower-limit 0 --base 1024
graph_vlabel bytes per ${graph_period}
graph_category freenet
graph_info Bandwidth usage

store.label input
store.type DERIVE
store.draw LINE
store.info Input

cache.label output
cache.type DERIVE
cache.draw LINE
cache.info Output

EOT;

} else {

echo <<<EOT
input.value   {$fcpData['volatile.totalInputBytes']}
output.value   {$fcpData['volatile.totalOutputBytes']}

EOT;

}


