#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

if($argc > 1 && $argv[1] == 'config') {

echo <<<EOT
graph_title Freenet ping time
graph_args --lower-limit 0
graph_vlabel ping time (ms)
graph_category freenet
graph_info Ping time of the node

ping.label ping time
ping.type GAUGE
ping.draw LINE
ping.info Ping time

EOT;

} else {

echo <<<EOT
ping.value {$fcpData['volatile.averagePingTime']}

EOT;

}


