#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

if($argc > 1 && $argv[1] == 'config') {

$type = $conf['areastacks'] ? 'AREASTACK' : 'LINE';

echo <<<EOT
graph_title Freenet peers
graph_args --lower-limit 0
graph_vlabel peers
graph_category freenet
graph_info Freenet peers we are connected to

connected.label connected
connected.type GAUGE
connected.draw $type
connected.info Peers we are routing requests to

busy.label backed off
busy.type GAUGE
busy.draw $type
busy.info Overloaded peers

tooold.label too old
tooold.type GAUGE
tooold.draw $type
tooold.info Those peers haven't a recent enough version of Freenet

seeding.label seeding for
seeding.type GAUGE
seeding.draw $type
seeding.info Peers we are seeding for

EOT;

} else {

echo <<<EOT
connected.value   {$fcpData['volatile.numberOfConnected']}
busy.value        {$fcpData['volatile.numberOfRoutingBackedOff']}
tooold.value      {$fcpData['volatile.numberOfTooOld']}
seeding.value	  {$fcpData['volatile.numberOfSeedClients']}

EOT;

}


