#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

if($argc > 1 && $argv[1] == 'config') {

$type = $config['areastacks'] ? 'AREASTACK' : 'LINE';

echo '
graph_title Freenet bandwidth usage
graph_args --lower-limit 0 --base 1024
graph_vlabel bytes per ${graph_period}
graph_category freenet
graph_info Bandwidth usage

input.label input
input.type DERIVE
input.draw '.$type.'
input.info Input

output.label output
output.type DERIVE
output.draw '.$type.'
output.info Output

';

} else {

$in = intval($fcpData['volatile.totalInputBytes']);
$out = intval($fcpData['volatile.totalOutputBytes']);

echo <<<EOT
input.value    $in
output.value   $out

EOT;

}


