#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

$upper = $conf['upper_datastore_access_limit'] ? $conf['upper_datastore_access_limit'] : 400;

if($argc > 1 && $argv[1] == 'config') {

echo '
graph_title Freenet datastore access rate
graph_args --lower-limit 0 --upper-limit '.$upper.' --rigid
graph_vlabel keys per ${graph_period}
graph_category freenet
graph_info Datastore access rate

store.label store
store.type DERIVE
store.min 0
store.draw LINE
store.info Store

cache.label cache
cache.type DERIVE
cache.min 0
cache.draw LINE
cache.info Cache

';

} else {

echo <<<EOT
store.value   {$fcpData['volatile.storeAccesses']}
cache.value   {$fcpData['volatile.cacheAccesses']}

EOT;

}


