#!/usr/bin/php
<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require dirname(realpath(__FILE__)).'/freenet_lib';

if($argc > 1 && $argv[1] == 'config') {

echo <<<EOT
graph_title Freenet thread count
graph_args --lower-limit 0
graph_vlabel threads
graph_category freenet
graph_info Number of threads used by the node

threads.label threads
threads.type GAUGE
threads.draw LINE
threads.info Number of threads used by the node

EOT;

} else {

echo <<<EOT
threads.value {$fcpData['volatile.runningThreadCount']}

EOT;

}


